### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by EzheG** [kakserpom/phpdaemon#200]
1. [x] Отдельное соединение для транзакций (multi) в Redis.
2. [ ] Вспомогательные методы в Redis:
  * [x] redisHashToArray
  * [x] RedisEval
  * [ ] scanKeys
3. [ ] Переписать чат на SockJS + Redis.
